/*
Nchf_OfflineOnlyCharging

OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.2.0-alpha.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PduSetQosParaRm PduSetQosPara with nullable: true
type PduSetQosParaRm struct {
	NullValue *NullValue
	PduSetQosPara *PduSetQosPara
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *PduSetQosParaRm) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into NullValue
	err = json.Unmarshal(data, &dst.NullValue);
	if err == nil {
		jsonNullValue, _ := json.Marshal(dst.NullValue)
		if string(jsonNullValue) == "{}" { // empty struct
			dst.NullValue = nil
		} else {
			return nil // data stored in dst.NullValue, return on the first match
		}
	} else {
		dst.NullValue = nil
	}

	// try to unmarshal JSON data into PduSetQosPara
	err = json.Unmarshal(data, &dst.PduSetQosPara);
	if err == nil {
		jsonPduSetQosPara, _ := json.Marshal(dst.PduSetQosPara)
		if string(jsonPduSetQosPara) == "{}" { // empty struct
			dst.PduSetQosPara = nil
		} else {
			return nil // data stored in dst.PduSetQosPara, return on the first match
		}
	} else {
		dst.PduSetQosPara = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(PduSetQosParaRm)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *PduSetQosParaRm) MarshalJSON() ([]byte, error) {
	if src.NullValue != nil {
		return json.Marshal(&src.NullValue)
	}

	if src.PduSetQosPara != nil {
		return json.Marshal(&src.PduSetQosPara)
	}

	return nil, nil // no data in anyOf schemas
}

type NullablePduSetQosParaRm struct {
	value *PduSetQosParaRm
	isSet bool
}

func (v NullablePduSetQosParaRm) Get() *PduSetQosParaRm {
	return v.value
}

func (v *NullablePduSetQosParaRm) Set(val *PduSetQosParaRm) {
	v.value = val
	v.isSet = true
}

func (v NullablePduSetQosParaRm) IsSet() bool {
	return v.isSet
}

func (v *NullablePduSetQosParaRm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePduSetQosParaRm(val *PduSetQosParaRm) *NullablePduSetQosParaRm {
	return &NullablePduSetQosParaRm{value: val, isSet: true}
}

func (v NullablePduSetQosParaRm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePduSetQosParaRm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


