/*
Nchf_OfflineOnlyCharging

Testing DefaultAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_DefaultAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultAPIService OfflinechargingdataOfflineChargingDataRefReleasePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var offlineChargingDataRef string

		httpRes, err := apiClient.DefaultAPI.OfflinechargingdataOfflineChargingDataRefReleasePost(context.Background(), offlineChargingDataRef).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService OfflinechargingdataOfflineChargingDataRefUpdatePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var offlineChargingDataRef string

		resp, httpRes, err := apiClient.DefaultAPI.OfflinechargingdataOfflineChargingDataRefUpdatePost(context.Background(), offlineChargingDataRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService OfflinechargingdataPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefaultAPI.OfflinechargingdataPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
