/*
 * Nchf_OfflineOnlyCharging
 *
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type DefaultAPI struct {
}

// Post /nchf-offlineonlycharging/v1/offlinechargingdata/:OfflineChargingDataRef/release
func (api *DefaultAPI) OfflinechargingdataOfflineChargingDataRefReleasePost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /nchf-offlineonlycharging/v1/offlinechargingdata/:OfflineChargingDataRef/update
func (api *DefaultAPI) OfflinechargingdataOfflineChargingDataRefUpdatePost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /nchf-offlineonlycharging/v1/offlinechargingdata
func (api *DefaultAPI) OfflinechargingdataPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

