/*
 * Nchf_OfflineOnlyCharging
 *
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// SteeringFunctionality - Indicates functionality to support traffic steering, switching and splitting determined by the PCF.   Possible values are   - MPTCP: Indicates that PCF authorizes the MPTCP functionality to support traffic   steering, switching and splitting.   - ATSSS_LL: Indicates that PCF authorizes the ATSSS-LL functionality to support traffic   steering, switching and splitting. 
type SteeringFunctionality struct {
}
