/*
 * Nchf_OfflineOnlyCharging
 *
 * OfflineOnlyCharging Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.2.0-alpha.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AccessTypeRm - Indicates wether the access is via 3GPP or via non-3GPP but with the OpenAPI  'nullable: true' property.\" 
type AccessTypeRm struct {
}
